/* watt-ffi — the C ABI the Android shell calls.
 *
 * Generated by hand from `core-rs/crates/watt-ffi/src/lib.rs`; keep the two in
 * step. Build the library with:
 *
 *     scripts/cargo.sh build -p watt-ffi --release --target aarch64-linux-android
 *
 * and it lands as `libwatt_ffi.so` under `target/aarch64-linux-android/release/`.
 * Put it in the app's `jniLibs/arm64-v8a/`.
 *
 * The Kotlin side needs two things and no more:
 *
 *   1. `VpnService.protect(fd)` behind `watt_protect_fn`. Without it the kernel's
 *      own upstream connections are captured by the tunnel it just created, and
 *      the relay loops. Measured on an emulator: sixteen client connections
 *      produced `tcp_open=2048` and not one byte came back. This is not optional
 *      and there is no fallback.
 *   2. A thread that calls `watt_engine_step` in a loop. The engine does not own
 *      a thread of its own, so shutdown stays the shell's decision.
 */

#ifndef WATT_FFI_H
#define WATT_FFI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque. Created by watt_engine_new, released by watt_engine_free. */
typedef struct WattEngine WattEngine;
typedef struct WattProxy WattProxy;

/* Called with a fresh upstream descriptor, before it is connected.
 *
 * This is where the shell calls `VpnService.protect(fd)`. Return non-zero for
 * the descriptor to be used; zero means it could not be protected, and the
 * connection is abandoned rather than handed back to the tunnel.
 *
 * Called from the engine's thread, not the one that built the engine. */
typedef int32_t (*watt_protect_fn)(void *ctx, int32_t fd);

/* Counters, filled in by watt_engine_stats. Plain integers so that JNI can read
 * them without matching Rust field ordering. */
typedef struct {
    uint64_t packets_in;
    uint64_t packets_out;
    uint64_t tcp_flows_opened;
    uint64_t tcp_flows_closed;
    uint64_t tcp_flows_rejected;
    uint64_t tcp_connect_failures;
    uint64_t udp_flows_opened;
    uint64_t udp_flows_evicted;
    uint64_t dns_queries;
    uint64_t dns_answered_locally;
    uint64_t dns_trimmed;
    uint64_t bytes_client_to_upstream;
    uint64_t bytes_upstream_to_client;
    uint64_t live_flows;
} WattStats;

/* Build an engine on the descriptor from `VpnService.establish()`.
 *
 * The descriptor is ADOPTED, NOT OWNED: closing it stays the shell's job,
 * because VpnService opened it and closing it twice would take a descriptor
 * belonging to something else.
 *
 * `tun_fd`    the ParcelFileDescriptor's fd, or -1 to fail.
 * `tun_name`  NUL-terminated, or NULL for "watt0".
 * `rules`     the rule document, `rules_len` bytes. Copied, not borrowed.
 * `protect`   required. A NULL callback is refused rather than defaulted.
 * `protect_ctx` passed back to `protect` unchanged; must outlive the engine.
 *
 * Returns NULL on failure. Call watt_last_error() for the reason. */
WattEngine *watt_engine_new(int32_t tun_fd,
                            const char *tun_name,
                            const uint8_t *rules,
                            size_t rules_len,
                            watt_protect_fn protect,
                            void *protect_ctx);

/* Merge two rule documents, unioning each domain's addresses.
 *
 * The two upstream sources are NOT the same format: one is JSON, the other is a
 * hosts file. `second_is_hosts` says which the second input is — guessing would
 * produce a confusing parse error rather than an obviously wrong answer.
 *
 * On success `*out_len` is set and the caller owns the buffer, releasing it with
 * watt_free_buffer(). Returns NULL on failure; read watt_last_error(). */
uint8_t *watt_merge_documents(const uint8_t *first,
                              size_t first_len,
                              const uint8_t *second,
                              size_t second_len,
                              int32_t second_is_hosts,
                              size_t *out_len);

/* Release a buffer from watt_merge_documents. */
void watt_free_buffer(uint8_t *buffer, size_t len);

/* Run one pass over the tunnel. Returns packets emitted, or -1 on failure. */
int32_t watt_engine_step(WattEngine *engine);

/* Swap in a new rule document. Flows already running are not disturbed.
 * Returns 0 on success, -1 on failure. */
int32_t watt_engine_replace_rules(WattEngine *engine,
                                  const uint8_t *rules,
                                  size_t rules_len);

/* Copy the counters out. Returns 0 on success, -1 on failure. */
int32_t watt_engine_stats(WattEngine *engine, WattStats *out);

/* Seconds since the engine was built. */
double watt_engine_uptime_seconds(WattEngine *engine);

/* Per-address byte history and per-(host, address) certificate verdicts, as a
 * NUL-terminated JSON object. Read-only: it reports what the kernel has already
 * learned and changes nothing on any data path.
 *
 *   { "addresses": [ { "ip": "140.82.112.6", "successes": 3, "failures": 1,
 *                      "silent": 0, "consecutive_failures": 0,
 *                      "ewma_rtt_ms": 247.3, "health": 0.75,
 *                      "in_cooldown": false, "since_success_ms": 1234,
 *                      "since_failure_ms": null } ],
 *     "certificates": [ { "host": "github.com", "ip": "140.82.112.6",
 *                         "verdict": "covers", "age_ms": 12000 } ] }
 *
 * `verdict` is one of "in_flight", "covers", "wrong_certificate",
 * "unreachable". A conclusion whose TTL has passed is omitted, so the report
 * never shows an address as rejected at the moment the dial path went back to
 * trying it. `ewma_rtt_ms` and the `since_*_ms` fields are null when the engine
 * has no such sample. Both arrays may be empty; both keys are always present.
 *
 * Returns NULL for a NULL engine. The caller owns the buffer, releasing it with
 * watt_free_buffer(); the length is strlen(buffer) + 1, the terminator included.
 */
char *watt_engine_ip_stats(WattEngine *engine);

/* Release an engine. NULL is a no-op, so teardown can call it unconditionally.
 * The adopted descriptor is NOT closed. */
void watt_engine_free(WattEngine *engine);

/* ---------------------------------------------------------------------------
 * CONNECT proxy
 *
 * The mode that needs neither TUN nor root. An app points its HTTP proxy at the
 * returned port and the listed domains are relayed.
 * ------------------------------------------------------------------------ */

/* Start a proxy on `port`, serving `rules`. Pass 0 to let the kernel choose a
 * free port; read it back with watt_proxy_port. Returns NULL on failure. */
WattProxy *watt_proxy_start(int32_t port, const uint8_t *rules, size_t rules_len);

/* The port actually bound. Returns 0 on a NULL handle. */
int32_t watt_proxy_port(WattProxy *proxy);

/* Swap in a new rule document without cutting in-flight CONNECTs. Only routing
 * decisions not yet made change. Returns 0 on success, -1 on failure. */
int32_t watt_proxy_replace_rules(WattProxy *proxy,
                                 const uint8_t *rules,
                                 size_t rules_len);

/* Stop the proxy and release the handle. NULL is a no-op. Blocks until the
 * accept loop has noticed, which is at most one idle poll. */
void watt_proxy_stop(WattProxy *proxy);

/* The last error on the calling thread, or NULL. Valid until the next failing
 * call on the same thread. Read it, do not free it. */
const char *watt_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* WATT_FFI_H */
